/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realestategui;

import javax.sql.*;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author csizmadiax.20d
 */
public class Ingatlan extends javax.swing.JFrame {
    /**
     * Creates new form Ingatlan
     */
    public Ingatlan() {
        initComponents();
        
        try{
            Connection connection =  DriverManager.getConnection("jdbc:mysql://localhost:3306/ingatlan?serverTimezone=UTC", "root", "");
            PreparedStatement preparedStatement=connection.prepareStatement("SELECT * FROM sellers");
            ResultSet resultSet = preparedStatement.executeQuery();
            connection.close();
            
            DefaultListModel listModel = new DefaultListModel();
            
            int i = 0;
            
            while(resultSet.next()){
                listModel.addElement(resultSet.getString(2));
                listEladok.setModel(listModel);
                i++;
            }
            
        }
        catch(SQLException exception){
            JOptionPane.showMessageDialog(null, exception);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listEladok = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHirdetesek = new javax.swing.JLabel();
        btnHirdetesek = new javax.swing.JButton();
        lblNev = new javax.swing.JLabel();
        lblTelefonszam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingatlanok");

        listEladok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listEladokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listEladok);

        jLabel1.setText("Eladó neve:");

        jLabel2.setText("Eladó telefonszáma:");

        jLabel3.setText("Hirdetések száma:");

        lblHirdetesek.setText("0");

        btnHirdetesek.setText("Hirdetések betöltése");
        btnHirdetesek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHirdetesekMouseClicked(evt);
            }
        });

        lblNev.setText("...");

        lblTelefonszam.setText("...");
        lblTelefonszam.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNev))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTelefonszam))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(63, 63, 63)
                        .addComponent(lblHirdetesek))
                    .addComponent(btnHirdetesek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNev))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTelefonszam))
                .addGap(18, 18, 18)
                .addComponent(btnHirdetesek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblHirdetesek))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listEladokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listEladokMouseClicked
        
        try {
            Connection connection =  DriverManager.getConnection("jdbc:mysql://localhost:3306/ingatlan?serverTimezone=UTC", "root", "");
            Statement stmt = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet resultSet = stmt.executeQuery("SELECT * FROM sellers");
            
            int index = listEladok.getSelectedIndex()+1;
            
            if(resultSet.absolute(index)){
                lblNev.setText(resultSet.getString(2));
                lblTelefonszam.setText(resultSet.getString(3));
            }
               
        } catch (SQLException exception) {
            JOptionPane.showMessageDialog(null, exception);
        }
        
    }//GEN-LAST:event_listEladokMouseClicked

    private void btnHirdetesekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHirdetesekMouseClicked
        
    }//GEN-LAST:event_btnHirdetesekMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingatlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingatlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingatlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingatlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingatlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHirdetesek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHirdetesek;
    private javax.swing.JLabel lblNev;
    private javax.swing.JLabel lblTelefonszam;
    private javax.swing.JList<String> listEladok;
    // End of variables declaration//GEN-END:variables
}
